name: marl_language_games
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.9.7
  - prettytable=3.0.0
  - tqdm=4.62.3
  - pytest=6.2.5
  - numpy=1.21.2
  - easydict=1.9
  - matplotlib=3.5.0
  - pandas=1.3.5
  - pyyaml=6.0
