name: emrl
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - blas=1.0
  - ca-certificates=2021.10.26
  - certifi=2021.10.8
  - easydict=1.9
  - importlib-metadata=4.8.2
  - intel-openmp=2021.4.0
  - libcxx=12.0.0
  - libffi=3.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.3
  - numpy=1.21.2
  - numpy-base=1.21.2
  - openssl=1.1.1l
  - pip=21.2.4
  - prettytable=3.0.0
  - python=3.9.6
  - python-dateutil=2.8.2
  - pyyaml=6.0
  - readline=8.1
  - setuptools=58.0.4
  - six=1.16.0
  - sqlite=3.37.0
  - tk=8.6.11
  - tqdm=4.62.3
  - tzdata=2021e
  - wcwidth=0.2.5
  - wheel=0.37.0
  - xz=5.2.5
  - yaml=0.2.5
  - zipp=3.6.0
  - zlib=1.2.11
