name: emrl
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - alabaster=0.7.12
  - appnope=0.1.2
  - astroid=2.6.6
  - attrs=21.2.0
  - babel=2.9.1
  - backcall=0.2.0
  - black=21.10b0
  - blas=1.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2021.10.26
  - certifi=2021.10.8
  - cffi=1.14.6
  - charset-normalizer=2.0.8
  - click=8.0.3
  - cloudpickle=1.6.0
  - colorama=0.4.4
  - cryptography=36.0.0
  - cycler=0.10.0
  - dataclasses=0.8
  - debugpy=1.4.1
  - decorator=5.0.9
  - docutils=0.16
  - easydict=1.9
  - ffmpeg=4.0
  - flake8=4.0.1
  - fonttools=4.27.1
  - freetype=2.10.4
  - future=0.18.2
  - gym=0.18.0
  - idna=3.1
  - imagesize=1.3.0
  - importlib-metadata=3.10.1
  - iniconfig=1.1.1
  - intel-openmp=2021.3.0
  - ipykernel=6.2.0
  - ipython=7.26.0
  - ipython_genutils=0.2.0
  - isort=5.10.1
  - jedi=0.18.0
  - jinja2=3.0.3
  - jpeg=9d
  - jupyter_client=6.1.12
  - jupyter_core=4.7.1
  - kiwisolver=1.3.1
  - lazy-object-proxy=1.6.0
  - lcms2=2.12
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcxx=10.0.0
  - libffi=3.3
  - libgfortran=3.0.1
  - libiconv=1.16
  - libopus=1.3.1
  - libpng=1.6.37
  - libsodium=1.0.18
  - libtiff=4.2.0
  - libvpx=1.7.0
  - libwebp-base=1.2.1
  - lz4-c=1.9.2
  - markupsafe=2.0.1
  - matplotlib=3.4.2
  - matplotlib-base=3.4.2
  - matplotlib-inline=0.1.2
  - mccabe=0.6.1
  - mkl=2021.3.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.2
  - more-itertools=8.11.0
  - munkres=1.1.4
  - mypy_extensions=0.4.3
  - ncurses=6.2
  - numpy=1.20.3
  - numpy-base=1.20.3
  - olefile=0.46
  - openssl=1.1.1l
  - packaging=21.2
  - parso=0.8.2
  - pathspec=0.9.0
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.2.0
  - pip=21.2.4
  - platformdirs=2.3.0
  - pluggy=1.0.0
  - prettytable=2.4.0
  - prompt-toolkit=3.0.17
  - ptyprocess=0.7.0
  - py=1.11.0
  - pycodestyle=2.8.0
  - pycparser=2.21
  - pydocstyle=6.1.1
  - pyflakes=2.4.0
  - pyglet=1.5.16
  - pygments=2.10.0
  - pylint=2.9.6
  - pyopenssl=21.0.0
  - pyparsing=2.4.7
  - pysocks=1.7.1
  - pytest=6.2.5
  - python=3.9.6
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytz=2021.3
  - pyyaml=5.4.1
  - pyzmq=22.2.1
  - readline=8.1
  - regex=2021.11.10
  - requests=2.26.0
  - scipy=1.6.2
  - setuptools=52.0.0
  - six=1.16.0
  - snowballstemmer=2.2.0
  - sphinx=4.3.0
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.5
  - sqlite=3.36.0
  - tk=8.6.10
  - toml=0.10.2
  - tomli=1.2.2
  - tornado=6.1
  - tqdm=4.62.3
  - traitlets=5.0.5
  - typed-ast=1.5.0
  - typing_extensions=4.0.0
  - tzdata=2021a
  - urllib3=1.26.7
  - wcwidth=0.2.5
  - wheel=0.37.0
  - wrapt=1.12.1
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.6.0
  - zlib=1.2.11
  - zstd=1.4.5
